### ISSUE TITLE
Can we pass the lodash options object?

### ISSUE THREAD

**Issue by Sjoerd82** [posva/pinia-plugin-debounce#39]
Lodash (not sure about ts-debounce, not familiar with that one) provides options besides the delay time. Can we pass an options object as well? In some cases I have a non-default leading/trailing requirement.

```
[options={}] (Object): The options object.
[options.leading=false] (boolean): Specify invoking on the leading edge of the timeout.
[options.maxWait] (number): The maximum time func is allowed to be delayed before it's invoked.
[options.trailing=true] (boolean): Specify invoking on the trailing edge of the timeout.
```

**Comment by posva** [comment]
You can't right now but this could be added with TS support as an array instead of a number:

```js
debounce: {
  someAction: [300, options]
}
```
